spring.application.name=todolist
server.port=8081

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/todolist
spring.datasource.username=todolist_user
spring.datasource.password=todolist_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
